### ISSUE TITLE
How to make the plot update (without clicking)?

### ISSUE THREAD

**Issue by rabernat** [Kitware/ipyvtk-simple#29] opened 2021-04-11 19:42 UTC
Thanks for providing this very cool package. I have been playing around with it a lot this weekend!

I am trying to create an interactive plot using pyvista and then update it from another cell. I find that my plot does not update until I _click_ on the plot output 

A simple example...
```python
import pyvista as pv
from pyvista import examples
import ipywidgets as widgets
pv.rcParams['use_ipyvtk'] = True

mesh = examples.load_hexbeam()
p = pv.Plotter()
p.add_mesh(mesh, show_edges=True)
p.show()
```

Then from _a different cell_, I move the camera
```python
bcpos = [(6.20, 3.00, 7.50),
         (0.16, 0.13, 2.65),
         (-0.28, 0.94, -0.21)]
p.camera_position = bcpos
```

Nothing happens until I actually click the plot. (I tried adding `p.update()`, but it had no effect.)

https://user-images.githubusercontent.com/1197350/114318646-f42c6e80-9adb-11eb-9b92-fb30d1afafa7.mov

This may seem like a small issue, but it really limits the ability to control the plot interactively. Is there a simple solution?

- Python 3.8.8
- Notebook Server 6.3.0 (not using lab)
- pyvista 0.29.0
- ipyvtk-simple 0.1.4

**Comment by banesullivan** [comment] 2021-04-12 15:45
We just need to tie the draw/update callback for the widget's image frame to the PyVista plotter's render event. Should be straightforward and I will work to fix this

**Comment by banesullivan** [comment] 2021-04-12 16:03
Actually, this might be kind of tricky.

We'll have to add several event listeners such that when anything in the scene is modified (e.g. a re-render, camera movement or a mesh is altered) to redraw the widget canvas.

**Comment by banesullivan** [comment] 2021-04-12 16:04
FYI, at the moment we have a timer set up to automatically redraw the canvas at specific intervals however, there can be significant lag so I would *not* consider that "interactive"

**Comment by banesullivan** [comment] 2021-04-13 22:59
https://github.com/pyvista/pyvista/pull/1264 should fix this issue for the camera adjustments at least. We still need to work out some event tracking for when a user alters the mesh geometry or data.

**Comment by banesullivan** [comment] 2021-04-14 03:42
This will be fixed in PyVista 0.30.0, coming soon (or currently by PyVista's main branch)

**Closed as completed** 2021-04-14 03:41 UTC

**Comment by rabernat** [comment] 2021-04-14 03:44
:tada: Amazing! Thanks Bane for your really fast response to this.

> [pyvista/pyvista#1264](https://github.com/pyvista/pyvista/pull/1264) should fix this issue for the camera adjustments at least. We still need to work out some event tracking for when a user alters the mesh geometry or data.

FWIW, I used camera movement in my issue because it was simple. But my actual real-world use case is for updating mesh data. (I want to animate a plot.) Should I open a new issue to track that, since it is still unresolved?

**Comment by banesullivan** [comment] 2021-04-14 04:28
Let's use https://github.com/pyvista/pyvista/issues/1262 to track this issue/use case as the problem is really in PyVista, not `ipyvtklink` (FYI, the name of this package just changed)
